version: '3'

services:
  react-ts:
    build: ./react-ts-app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    
  go:
    build: ./go-app
    ports:
      - '8000:8000'
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
    # MYSQL_ROOT_PASSWORDのみをenvファイルで設定
    env_file:
      - variables.env
    ports:
      - '3306:3306'
